name: Run Test Suite on CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.1

    - name: Chrome Install
      uses: browser-actions/setup-chrome@latest
      with:
        chrome-version: stable

    - name: Bundle Install
      run: |
        gem install bundler
        bundle install

    - name: NPM Install
      run: npm install

    - name: Run All the Cucumber Tests - skip wip
      run: |
        CHROMIUM_BIN=$(which chrome) \
        PERCY_TOKEN=${{ secrets.PERCY_TOKEN }} \
        PERCY_BROWSER_EXECUTABLE==$(which chrome) \
        PUPPETEER_EXECUTABLE_PATH=$(which chrome) \
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true \
        CHROME_HEADLESS=true \
        CI=true \
        npx percy exec -- bundle exec cucumber --tags 'not @wip'
